apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: nodeport
    env: dev
spec:
  type: NodePort
  ports:
    - nodePort: 30001  #list or array hence - used
      port: 80
      targetPort: 80
  selector:
      env: dev

