apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:

  initContainers:
  - name: create-html
    image: busybox
    command:
    - sh
    - -c
    - echo "Welcome to Kubernetes Init Container" > /work-dir/index.html
    volumeMounts:
    - name: web-data
      mountPath: /work-dir

  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-data
      mountPath: /usr/share/nginx/html

  volumes:
  - name: web-data
    emptyDir: {}