apiVersion: v1
kind: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.ip/service-account.name: build-sa             # this annotations is creating the secret and attaching with the service account (which is build-sa)
type: kubernetes.io/service-account-token                    # this secret is a type of service account token



