#ConfigMap 
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config

data:
  app.conf: |
    server=nginx
    port=80

---

#ConfigMap as Volume
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: config-volume
      mountPath: /etc/config

  volumes:
  - name: config-volume
    configMap:
      name: web-config