apiVersion: v1
kind: Pod
metadata:
  name: webapp
  
spec:
  containers:
  - name: webapp
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]

    env:
    - name: DB_SERVICE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_SERVICE

    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_PORT