#using secret as env variable
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","env && sleep 3600"]

    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: username

    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password

---

#import entire Secret replace env with envFrom
envFrom:
- secretRef:
    name: mysql-secret