apiVersion: v1
kind: Pod
metadata:
  name: golang-api

spec:
  containers:
  - name: golang-app
    image: company/customer-api:v1
    
    volumeMounts:
    - name: applogs
      mountPath: /logs

  - name: fluentbit
    image: fluent/fluent-bit

    volumeMounts:
    - name: applogs
      mountPath: /logs

  volumes:
  - name: applogs
    emptyDir: {}